export default {
  products: [
    {
      _id: "1",
      name: "스탠 칼라 스트링 숏 아우터 - 블랙",
      category: "Shirts",
      image: "/images/1.webp",
      brand: "8seconds",
      rating: 4.8,
      price: 60,
      numOfReviews: 200,
      countInStock: 6,
    },
    {
      _id: "2",
      name: "Chips Stacking Mug – Grey",
      category: "Shirts",
      image: "/images/2.jpeg",
      brand: "8seconds",
      rating: 4.5,
      price: 60,
      numOfReviews: 88,
      countInStock: 6,
    },
    {
      _id: "3",
      name: "스탠 칼라 스트링 숏 아우터 - 블랙",
      category: "Shirts",
      image: "/images/3.webp",
      brand: "8seconds",
      rating: 4.5,
      price: 60,
      numOfReviews: 6,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Chips Stacking Mug – Grey",
      category: "Shirts",
      image: "/images/4.webp",
      brand: "8seconds",
      rating: 4.5,
      price: 60,
      numOfReviews: 51,
      countInStock: 6,
    },
    {
      _id: "4",
      name: "Chips Stacking Mug – Grey",
      category: "Shirts",
      image: "/images/5.webp",
      brand: "8seconds",
      rating: 2.8,
      price: 60,
      numOfReviews: 40,
      countInStock: 6,
    },
  ],
};
